// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// prisma.config.ts
import 'dotenv/config'; // Loads your .env file
import { defineConfig, env } from 'prisma/config';

export default defineConfig({
  schema: 'prisma/schema.prisma', // Path to your schema file
  datasource: {
    url: env('DATABASE_URL'), // Your DB connection string from .env
  },
});